services:
  - type: web
    name: powder
    env: python
    buildCommand: |
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      npm install
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt --no-cache-dir
      chmod +x getForecastFull_all_resorts.py
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 3000
      - key: PYTHON_VERSION
        value: "3.9"
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATA_DIR
        value: /opt/render/project/data
    runtime: "python3"