services:
  - type: web
    name: powder
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update
      apt-get install -y python3-pip python3-dev python3-venv build-essential

      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

      # Install npm dependencies
      npm install

      # Create and activate virtual environment
      python3 -m venv venv
      . venv/bin/activate

      # Install Python packages in virtual environment
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt

      # Make Python script executable
      chmod +x getForecastFull_all_resorts.py

      # Debug information
      echo "Installed Python packages:"
      pip list
      echo "Python version:"
      python3 --version
      echo "Pip version:"
      pip --version
    startCommand: |
      . venv/bin/activate  # Activate virtual environment
      pip list  # Log installed packages at startup
      node app.js
    envVars:
      - key: PORT
        value: 3000
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PYTHONPATH
        value: /opt/render/project/src/venv/lib/python3.11/site-packages
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATA_DIR
        value: /opt/render/project/data
    runtime: "python3"