services:
  - type: web
    name: powder
    env: node
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 3000
    runtime: python3